### ISSUE TITLE
Warning: Cannot read property 'recursive' of undefined

### ISSUE THREAD

**Issue by martinkr** [mmacmillan/grunt-jsdox#14] opened 2014-10-21 13:20 UTC
Hey, running your example task throws "Warning: Cannot read property 'recursive' of undefined Use --force to continue.". Unfortunately: every run results in this error. 

Running "example" task
[D] Task source: node_modules/grunt-jsdox/Gruntfile.js

Running "jsdox:generate" (jsdox) task
[D] Task source: tasks/jsdox.js
Verifying property jsdox.generate exists in config...OK
Files: example/code/folder1/moduleA.js, example/code/folder1/moduleB.js, example/code/folder1/moduleC.js, example/code/folder2/moduleA.js, example/code/folder2/moduleB.js, example/code/folder2/moduleC.js, example/code/folder2/subfolder1/moduleA.js, example/code/folder2/subfolder1/moduleB.js, example/code/folder2/subfolder1/moduleC.js, example/code/moduleA.js, example/code/moduleB.js, example/code/moduleC.js -> example/docs
Options: contentsEnabled, contentsFile="readme.md", contentsTitle="Example Documentation", templateDir=null, pathFilter={}
Warning: Cannot read property 'recursive' of undefined Use --force to continue.

**Comment by psq** [comment] 2014-10-21 21:09
probably broken by a recent change in jsdox.  Will look into it.

**Comment by meditation-error** [comment] 2014-11-25 10:45
Im running into the same error when running jsdox on osx yosemite on 2 machines, another machine with mavericks still installed does not have this issue.

It looks like it has something todo with the osx notification center: the last couple of lines of the grunt task with --verbose:

> > [grunt-notify] IS_WINDOWS: false
> > [grunt-notify] PROGRAM_FILES: undefined
> > [grunt-notify] PROGRAM_FILES_X86: undefined
> > [grunt-notify] fullPathToApplication: false
> > [grunt-notify] snarl: Snarl not available for this OS.
> > [grunt-notify] os: Darwin
> > [grunt-notify] version: 14.0.0
> > [grunt-notify] IS_MAC: true
> > [grunt-notify] MOUNTAIN_LION: true
> > [grunt-notify] notification_center: Will use Notification Center
> > [notification-center] cmd: /myApp/node_modules/grunt-notify/bin/Grunt.app/Contents/MacOS/Grunt
> > [notification-center] args: -title myApp -message Cannot read property 'recursive' of undefined
> > Warning: Cannot read property 'recursive' of undefined Use --force to continue.

(Maybe the issue is more grunt-notify related, but using jsdox is the only time grunt-notify is giving this problem in my environment.)

**Comment by mrjoelkemp** [comment] 2014-11-25 13:33
I'll fix this today. Thanks for filing the issue.

Fixed in https://github.com/sutoiku/jsdox/pull/75. Need to merge in and cut a new release of grunt-jsdox.

**Comment by mrjoelkemp** [comment] 2014-11-25 21:58
This should be fixed if you reinstall grunt-jsdox. Version 0.4.4 of jsdox has the patch.

**Closed as completed by mrjoelkemp** 2014-11-25 21:58 UTC

**Comment by meditation-error** [comment] 2014-11-26 07:16
Thanks, everything works great again now :)
